task_attributes:
  vqa:
    datasets:
    - verbal_spatial
    dataset_attributes:
      verbal_spatial:
        data_root_dir: 
        feat_folder: 
        vqamb_path: 

        # folder containing point-supervision features
        feat_folder: looktwice_imgs

        # whether to pad detectron features (usually true)
        pad_detectron: True
        
        # whether to use spatial or verbal disambiguation
        spatial: False
        
        processors:
          text_processor:
            type: vocab
            params:
              max_length: 13 # maximum length of question in VQAmb Dataset
              vocab:
                type: intersected
                embedding_name: glove.6B.300d
                vocab_file: vocabs/verbal_vg_vocab.txt

            preprocessor:
              type: simple_sentence
              params: {}

          answer_processor:
            type: multi_hot_answer_from_vocab
            params:
              vocab_file: vocabs/verbal_vg_answers.txt
              preprocessor:
                type: simple_word
                params: {}



