task_attributes:
  vqa:
    datasets:
    - vqamb
    dataset_attributes:
      vqamb:
        data_root_dir: 
        feat_folder: 
        vqamb_path: 

        # folder containing point-supervision features
        pt_feat_folder: vqamb_ptnms

        # whether to pad detectron features (usually true)
        pad_detectron: True

        # whether to use region or grid features
        grid: False
        
        processors:
          text_processor:
            type: vocab
            params:
              max_length: 7 # maximum length of question in VQAmb Dataset
              vocab:
                type: intersected
                embedding_name: glove.6B.300d
                vocab_file: vocabs/vqamb_new_vocab.txt

            preprocessor:
              type: simple_sentence
              params: {}

          answer_processor:
            type: multi_hot_answer_from_vocab
            params:
              vocab_file: vocabs/vqamb_new_answers.txt
              preprocessor:
                type: simple_word
                params: {}



